### ISSUE TITLE
Add support for non-static classes for GenerateApplicationProperties task

### ISSUE THREAD

**Issue by u-ways** [propactive/propactive#14]
The current implementation of `io.github.propactive.task.GenerateApplicationProperties` only expects a static class (i.e. object in Kotlin) as an eligible class for Propactive. Therefore, a given application properties object of:

```
@Environment
object EligibleClass {
    @Property(["value"])
    const val property = "example.resource.key"
}
```

Will work just fine, however:

```
@Environment
class IneligibleClass {
    @Property(["value"])
    val property = "example.resource.key"
}
```

will fail with the following log:

```log
Callable expects 1 arguments, but 0 were provided.
java.lang.IllegalArgumentException: Callable expects 1 arguments, but 0 were provided.
	at kotlin.reflect.jvm.internal.calls.Caller$DefaultImpls.checkArguments(Caller.kt:20)
	at kotlin.reflect.jvm.internal.calls.CallerImpl.checkArguments(CallerImpl.kt:15)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:112)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at io.github.propactive.property.PropertyFactory.create(PropertyFactory.kt:31)
	at io.github.propactive.environment.EnvironmentFactory.create(EnvironmentFactory.kt:21)
	at io.github.propactive.task.GenerateApplicationProperties.invoke$propactive_plugin(GenerateApplicationProperties.kt:52)
	at io.github.propactive.task.GenerateApplicationPropertiesTest$shouldAllowApplicationPropertiesFilenameOverrideWhenASingularEnvironmentApplicationPropertiesHasBeenGenerated$1.invoke(GenerateApplicationPropertiesTest.kt:79)
	at io.github.propactive.task.GenerateApplicationPropertiesTest$shouldAllowApplicationPropertiesFilenameOverrideWhenASingularEnvironmentApplicationPropertiesHasBeenGenerated$1.invoke(GenerateApplicationPropertiesTest.kt:73)
```

The issue seems to be straightforward to fix. (i.e. reflect non-static class instances differently). Although, when such feature is added, perhaps we should consider giving easy to understand errors for when the class is expecting multiple property arguments/fields on runtime and none are provided by default? Or perhaps an error to indicate we don't support classes with unresolved property arguments/fields?

**Comment by u-ways** [comment]
Closing this for now as with the current design candidate for Propactive 2.0.0, this is no longer required.  (i.e. Inversion of control of object from the plugin, to the user)
